environment:
  CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
  matrix:
    - TARGET_ARCH: x64
      NPY: 1.15
      PY: 3.6

    - TARGET_ARCH: x64
      NPY: 1.15
      PY: 3.7

platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    # credits: JuliaLang developers.
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
         https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
         Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
           throw "There are newer queued builds for this pull request, failing early." }

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe config --set always_yes yes --set changeps1 no --set show_channel_urls true
    - cmd: conda.exe update conda
    - cmd: conda.exe config --remove channels defaults --force
    - cmd: conda.exe config --add channels conda-forge --force

    - cmd: set PYTHONUNBUFFERED=1

    - cmd: conda.exe install conda-build vs2008_express_vc_python_patch
    - cmd: call setup_x64
    - cmd: conda.exe info --all
    - cmd: conda.exe list

# Skip .NET project specific build phase.
build: off

test_script:
    - conda.exe create --name TEST python=%PY% numpy=%NPY% cython pip pytest pytest-cov
    - conda activate TEST
    - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    - py.test -vv tests
