{% set version = "dev" %}

package:
  name: netcdftime
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - setuptools
    - numpy x.x

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - netcdftime
  commands:
    - py.test -vv test

about:
  home: https://github.com/Unidata/netcdftime
  license: OSI Approved
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library..'
