name: cftime test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        platform: [x64, x32]
#  debug on a single os/platform/python version
#       python-version: [ "3.9"]
#       os: [ubuntu-latest]
#       platform: [x64]
        exclude:
          - os: macos-latest  
            platform: x32

    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      TRAVIS_REPO_SLUG: ${{ github.repository }}

    steps:

    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Setup Conda Env
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt
        source activate TEST
        # enabling coverage slows down the tests dramaticaly
        #CYTHON_COVERAGE=1 pip install -v -e  . --no-deps --force-reinstall
        pip install -v -e  . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -l {0}
      run: |
        source activate TEST
        py.test -vv test

#   - name: Coveralls
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     if: ${{ matrix.os =='ubuntu-latest' && matrix.python-version == '3.9' && matrix.platform == 'x64' }}
#     run: |
#       source activate TEST
#       coveralls --service=github-actions

    - name: Tarball
      if: startsWith(matrix.os,'ubuntu')
      shell: bash -l {0}
      run: |
        source activate TEST
        python setup.py --version ; 
        pip wheel . -w dist --no-deps ;
        check-manifest --verbose ;
        twine check dist/* ;
 
    - name: Docs
      if: startsWith(matrix.os,'ubuntu')
      shell: bash -l {0}
      run: |
        source activate TEST
        pushd docs && make html linkcheck O=-W && popd;
        #rm -f docs/build/html/_static/jquery-*.js
        #rm -f docs/build/html/_static/underscore-*.js
        #rm -f docs/build/html/.buildinfo
        #sh ./ci/deploy_docs.sh

  run_aarch64:
    name: "run (${{ matrix.pyver }}, aarch64)"
    strategy:
      matrix:
        pyver: [cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
      python-version: ${{ matrix.pyver }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Build and Test
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc 'yum install -y wget && \
          echo "Set Up Conda Env" && \
          wget https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh -O miniconda.sh && \
          export MINICONDA_PATH=/root/miniconda && \
          chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH && \
          export PATH=$MINICONDA_PATH/bin:$PATH && \
          export Python=${{ env.python-version }} && \
          conda create --name TEST python=${Python:2:1}.${Python:3:1} --file requirements.txt --file requirements-dev.txt && \
          source activate TEST && \
          pip install -v -e  . --no-deps --force-reinstall && \
          conda info --all && \
          conda list && \
          py.test -vv test && \
          python setup.py --version && \
          pip wheel . -w dist --no-deps && \
          check-manifest --verbose && \
          pip install readme-renderer && \
          twine check dist/* && \
          deactivate'
